export const allProductsActionTypes={
    FETCHING_ALL_PRODUCTS_STARTS:"FETCHING_ALL_PRODUCTS_STARTS",
    FETCHING_ALL_PRODUCTS_SUCCESS:"FETCHING_ALL_PRODUCTS_SUCCESS",
    FETCHING_ALL_PRODUCTS_FAILURE:"FETCHING_ALL_PRODUCTS_FAILURE",
}
export const productDetailsActionTypes={
    FETCHING_PRODUCT_STARTS:"FETCHING_PRODUCT_STARTS",
    FETCHING_PRODUCT_SUCCESS:"FETCHING_PRODUCT_SUCCESS",
    FETCHING_PRODUCT_FAILURE:"FETCHING_PRODUCT_FAILURE",
}